name: Deploy to ECS

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up AWS credentials
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Log in to Amazon ECR (no need for region input here)
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: false
          registry-type: private
          skip-logout: false

      # Build Docker image
      - name: Build Docker image
        run: docker build -t my-app .

      # Tag Docker image
      - name: Tag Docker image
        run: docker tag my-app:latest 637423496095.dkr.ecr.eu-north-1.amazonaws.com/taskmaster-repo

      # Push Docker image to ECR
      - name: Push Docker image to ECR
        run: docker push 637423496095.dkr.ecr.eu-north-1.amazonaws.com/taskmaster-repo

      # Push Docker image to ECR
      - name: Push Docker image to ECR
        run: docker push 637423496095.dkr.ecr.eu-north-1.amazonaws.com/taskmaster-repo

